package ptut.vue;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Florian Hauwelle
 */
public class FenAccueil extends javax.swing.JFrame {

    public FenAccueil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGroup_promo = new javax.swing.ButtonGroup();
        pannBouton1 = new javax.swing.JPanel();
        bt_addProduit1 = new javax.swing.JButton();
        bt_modifier1 = new javax.swing.JButton();
        bt_supprimer1 = new javax.swing.JButton();
        jTabbedPane_onglets = new javax.swing.JTabbedPane();
        tabPannProduits = new javax.swing.JPanel();
        pannCatalogueProduits = new javax.swing.JPanel();
        lbl_rechercheNom = new javax.swing.JLabel();
        tf_rechercheNom = new javax.swing.JTextField();
        lbl_rechercheCategorie = new javax.swing.JLabel();
        cbb_rechercheCategorie = new javax.swing.JComboBox<>();
        bt_rechercheProduit = new javax.swing.JButton();
        bt_rechercheProduitEffacer = new javax.swing.JButton();
        pannCaractProduit = new javax.swing.JPanel();
        lbl_id = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        lbl_prix = new javax.swing.JLabel();
        tf_prix = new javax.swing.JTextField();
        lbl_categorie = new javax.swing.JLabel();
        cbb_categorie = new javax.swing.JComboBox<>();
        lbl_nom = new javax.swing.JLabel();
        tf_nom = new javax.swing.JTextField();
        lbl_description = new javax.swing.JLabel();
        lbl_promotion = new javax.swing.JLabel();
        rbt_oui = new javax.swing.JRadioButton();
        rbt_non = new javax.swing.JRadioButton();
        lbl_prixPromo = new javax.swing.JLabel();
        tf_prixPromo = new javax.swing.JTextField();
        lbl_stock = new javax.swing.JLabel();
        tf_stock = new javax.swing.JTextField();
        lbl_image = new javax.swing.JLabel();
        bt_parcourir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tf_seuilAlerteStock = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        ta_descriptionCategorie1 = new javax.swing.JTextArea();
        pannBoutonProduit = new javax.swing.JPanel();
        bt_addProduit = new javax.swing.JButton();
        bt_modifierProduit = new javax.swing.JButton();
        bt_supprimer = new javax.swing.JButton();
        tabPannCategories = new javax.swing.JPanel();
        pannRechercheCategorie = new javax.swing.JPanel();
        lbl_categorie1 = new javax.swing.JLabel();
        cbb_categorie2 = new javax.swing.JComboBox<>();
        bt_rechercheCategorie = new javax.swing.JButton();
        pannCategorie = new javax.swing.JPanel();
        lbl_IdCategorie = new javax.swing.JLabel();
        tf_IdCategorie = new javax.swing.JTextField();
        lbl_nomCategorie = new javax.swing.JLabel();
        lbl_descriptionCategorie = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_descriptionCategorie = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tf_nomCategorie = new javax.swing.JTextField();
        lbl_nbProduit = new javax.swing.JLabel();
        tf_nbProduits = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pannBoutonCategorie = new javax.swing.JPanel();
        bt_addCategorie = new javax.swing.JButton();
        bt_modifCategorie = new javax.swing.JButton();
        bt_supprCategorie = new javax.swing.JButton();
        tabPannPromotion = new javax.swing.JPanel();
        tabPannClients = new javax.swing.JPanel();
        pannRechercheClient = new javax.swing.JPanel();
        lbl_rechercheIdClient = new javax.swing.JLabel();
        tf_rechercheClient = new javax.swing.JTextField();
        bt_rechercheClient = new javax.swing.JButton();
        bt_rechercheClientEffacer = new javax.swing.JButton();
        lbl_listeClient = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_listeClient = new javax.swing.JTable();
        pannFicheClient = new javax.swing.JPanel();
        lbl_idClient = new javax.swing.JLabel();
        tf_idClient = new javax.swing.JTextField();
        lbl_inscription = new javax.swing.JLabel();
        ftf_inscription = new javax.swing.JFormattedTextField();
        lbl_nomClient = new javax.swing.JLabel();
        tf_nomClient = new javax.swing.JTextField();
        lbl_prenomClient = new javax.swing.JLabel();
        tf_prenomClient = new javax.swing.JTextField();
        lbl_emailClient = new javax.swing.JLabel();
        tf_emailClient = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_commande = new javax.swing.JTable();
        bt_commandeClient = new javax.swing.JButton();

        bt_addProduit1.setText("Ajouter produit");
        bt_addProduit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_addProduit1MouseClicked(evt);
            }
        });
        bt_addProduit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addProduit1ActionPerformed(evt);
            }
        });

        bt_modifier1.setText("Modifier");
        bt_modifier1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_modifier1MouseClicked(evt);
            }
        });

        bt_supprimer1.setText("Supprimer");
        bt_supprimer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_supprimer1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pannBouton1Layout = new javax.swing.GroupLayout(pannBouton1);
        pannBouton1.setLayout(pannBouton1Layout);
        pannBouton1Layout.setHorizontalGroup(
            pannBouton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannBouton1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(bt_addProduit1)
                .addGap(87, 87, 87)
                .addComponent(bt_modifier1)
                .addGap(96, 96, 96)
                .addComponent(bt_supprimer1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pannBouton1Layout.setVerticalGroup(
            pannBouton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannBouton1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pannBouton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_addProduit1)
                    .addComponent(bt_modifier1)
                    .addComponent(bt_supprimer1))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Application gestion de stock");

        jTabbedPane_onglets.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tabPannProduits.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pannCatalogueProduits.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Catalogue des produits"));

        lbl_rechercheNom.setText("Nom");

        tf_rechercheNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_rechercheNomActionPerformed(evt);
            }
        });

        lbl_rechercheCategorie.setText("Catégorie");

        cbb_rechercheCategorie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Arbres", "Fleurs", "Plantes grasses" }));
        cbb_rechercheCategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_rechercheCategorieActionPerformed(evt);
            }
        });

        bt_rechercheProduit.setText("Rechercher");
        bt_rechercheProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_rechercheProduitActionPerformed(evt);
            }
        });

        bt_rechercheProduitEffacer.setText("Effacer");
        bt_rechercheProduitEffacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_rechercheProduitEffacerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pannCatalogueProduitsLayout = new javax.swing.GroupLayout(pannCatalogueProduits);
        pannCatalogueProduits.setLayout(pannCatalogueProduitsLayout);
        pannCatalogueProduitsLayout.setHorizontalGroup(
            pannCatalogueProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannCatalogueProduitsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pannCatalogueProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_rechercheCategorie)
                    .addComponent(lbl_rechercheNom, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pannCatalogueProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_rechercheNom, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbb_rechercheCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannCatalogueProduitsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_rechercheProduit)
                .addGap(63, 63, 63)
                .addComponent(bt_rechercheProduitEffacer)
                .addGap(61, 61, 61))
        );
        pannCatalogueProduitsLayout.setVerticalGroup(
            pannCatalogueProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannCatalogueProduitsLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pannCatalogueProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_rechercheNom)
                    .addComponent(tf_rechercheNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(pannCatalogueProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_rechercheCategorie)
                    .addComponent(cbb_rechercheCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(pannCatalogueProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_rechercheProduit)
                    .addComponent(bt_rechercheProduitEffacer)))
        );

        pannCaractProduit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_id.setText("ID/Réf.");

        lbl_prix.setText("Prix");

        tf_prix.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_prixKeyTyped(evt);
            }
        });

        lbl_categorie.setText("Catégorie");

        cbb_categorie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Arbres", "Fleurs", "Plantes grasses" }));
        cbb_categorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_categorieActionPerformed(evt);
            }
        });

        lbl_nom.setText("Nom");

        lbl_description.setText("Description");

        lbl_promotion.setText("Promotion");

        btGroup_promo.add(rbt_oui);
        rbt_oui.setText("Oui");

        btGroup_promo.add(rbt_non);
        rbt_non.setText("Non");
        rbt_non.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_nonActionPerformed(evt);
            }
        });

        lbl_prixPromo.setText("Prix promo");

        tf_prixPromo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_prixPromoKeyTyped(evt);
            }
        });

        lbl_stock.setText("Stock");

        tf_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_stockActionPerformed(evt);
            }
        });
        tf_stock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_stockKeyTyped(evt);
            }
        });

        bt_parcourir.setText("Parcourir..");
        bt_parcourir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_parcourirActionPerformed(evt);
            }
        });

        jLabel1.setText("Seuil stock alerte");

        tf_seuilAlerteStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_seuilAlerteStockKeyTyped(evt);
            }
        });

        jScrollPane4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ta_descriptionCategorie1.setColumns(20);
        ta_descriptionCategorie1.setRows(5);
        ta_descriptionCategorie1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane4.setViewportView(ta_descriptionCategorie1);

        javax.swing.GroupLayout pannCaractProduitLayout = new javax.swing.GroupLayout(pannCaractProduit);
        pannCaractProduit.setLayout(pannCaractProduitLayout);
        pannCaractProduitLayout.setHorizontalGroup(
            pannCaractProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannCaractProduitLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pannCaractProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pannCaractProduitLayout.createSequentialGroup()
                        .addGroup(pannCaractProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_prix, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_promotion)
                            .addComponent(lbl_prixPromo)
                            .addComponent(lbl_id))
                        .addGroup(pannCaractProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pannCaractProduitLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tf_prixPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pannCaractProduitLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(pannCaractProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_prix, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pannCaractProduitLayout.createSequentialGroup()
                                        .addComponent(rbt_oui)
                                        .addGap(33, 33, 33)
                                        .addComponent(rbt_non))
                                    .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pannCaractProduitLayout.createSequentialGroup()
                        .addGroup(pannCaractProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_description)
                            .addComponent(lbl_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pannCaractProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addGroup(pannCaractProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pannCaractProduitLayout.createSequentialGroup()
                        .addGroup(pannCaractProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_categorie)
                            .addComponent(bt_parcourir))
                        .addGap(18, 18, 18)
                        .addGroup(pannCaractProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pannCaractProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbb_categorie, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pannCaractProduitLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_seuilAlerteStock, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pannCaractProduitLayout.setVerticalGroup(
            pannCaractProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannCaractProduitLayout.createSequentialGroup()
                .addGroup(pannCaractProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pannCaractProduitLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(pannCaractProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_id)
                            .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_prix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannCaractProduitLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pannCaractProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nom)
                            .addComponent(tf_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pannCaractProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_prix)
                            .addComponent(lbl_categorie)
                            .addComponent(cbb_categorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(pannCaractProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pannCaractProduitLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(lbl_stock))
                    .addGroup(pannCaractProduitLayout.createSequentialGroup()
                        .addGroup(pannCaractProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_promotion)
                            .addComponent(rbt_oui)
                            .addComponent(rbt_non))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pannCaractProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_prixPromo)
                            .addComponent(tf_prixPromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pannCaractProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_description)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pannCaractProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(tf_seuilAlerteStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pannCaractProduitLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pannCaractProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_parcourir))))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        bt_addProduit.setText("Ajouter produit");
        bt_addProduit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_addProduitMouseClicked(evt);
            }
        });
        bt_addProduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addProduitActionPerformed(evt);
            }
        });

        bt_modifierProduit.setText("Modifier");
        bt_modifierProduit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_modifierProduitMouseClicked(evt);
            }
        });

        bt_supprimer.setText("Supprimer");
        bt_supprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_supprimerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pannBoutonProduitLayout = new javax.swing.GroupLayout(pannBoutonProduit);
        pannBoutonProduit.setLayout(pannBoutonProduitLayout);
        pannBoutonProduitLayout.setHorizontalGroup(
            pannBoutonProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannBoutonProduitLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(bt_addProduit)
                .addGap(87, 87, 87)
                .addComponent(bt_modifierProduit)
                .addGap(96, 96, 96)
                .addComponent(bt_supprimer)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        pannBoutonProduitLayout.setVerticalGroup(
            pannBoutonProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannBoutonProduitLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pannBoutonProduitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_addProduit)
                    .addComponent(bt_modifierProduit)
                    .addComponent(bt_supprimer))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tabPannProduitsLayout = new javax.swing.GroupLayout(tabPannProduits);
        tabPannProduits.setLayout(tabPannProduitsLayout);
        tabPannProduitsLayout.setHorizontalGroup(
            tabPannProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPannProduitsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabPannProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pannCatalogueProduits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tabPannProduitsLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(pannBoutonProduit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(pannCaractProduit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tabPannProduitsLayout.setVerticalGroup(
            tabPannProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPannProduitsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pannCatalogueProduits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pannCaractProduit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pannBoutonProduit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane_onglets.addTab("Produits", tabPannProduits);

        pannRechercheCategorie.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Rechercher une catégorie"));

        lbl_categorie1.setText("Catégorie");

        cbb_categorie2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Arbres", "Fleurs", "Plantes grasses" }));

        bt_rechercheCategorie.setText("Rechercher");
        bt_rechercheCategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_rechercheCategorieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pannRechercheCategorieLayout = new javax.swing.GroupLayout(pannRechercheCategorie);
        pannRechercheCategorie.setLayout(pannRechercheCategorieLayout);
        pannRechercheCategorieLayout.setHorizontalGroup(
            pannRechercheCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannRechercheCategorieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_categorie1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbb_categorie2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(bt_rechercheCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pannRechercheCategorieLayout.setVerticalGroup(
            pannRechercheCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannRechercheCategorieLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pannRechercheCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_categorie1)
                    .addComponent(cbb_categorie2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_rechercheCategorie))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pannCategorie.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_IdCategorie.setText("ID Catégorie");

        lbl_nomCategorie.setText("Nom Catégorie");

        lbl_descriptionCategorie.setText("Description");

        jScrollPane3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ta_descriptionCategorie.setColumns(20);
        ta_descriptionCategorie.setRows(5);
        ta_descriptionCategorie.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane3.setViewportView(ta_descriptionCategorie);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID produit", "Libellé produit", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable1);

        lbl_nbProduit.setText("Nb produits inclus");

        tf_nbProduits.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_nbProduitsKeyTyped(evt);
            }
        });

        jLabel2.setText("Produits inclus dans la catégorie");

        javax.swing.GroupLayout pannCategorieLayout = new javax.swing.GroupLayout(pannCategorie);
        pannCategorie.setLayout(pannCategorieLayout);
        pannCategorieLayout.setHorizontalGroup(
            pannCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannCategorieLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pannCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pannCategorieLayout.createSequentialGroup()
                        .addGroup(pannCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_IdCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_nomCategorie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pannCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pannCategorieLayout.createSequentialGroup()
                                .addComponent(tf_nomCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7))
                            .addComponent(tf_IdCategorie)))
                    .addComponent(lbl_descriptionCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(pannCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannCategorieLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannCategorieLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannCategorieLayout.createSequentialGroup()
                        .addComponent(lbl_nbProduit)
                        .addGap(44, 44, 44)
                        .addComponent(tf_nbProduits, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))))
        );
        pannCategorieLayout.setVerticalGroup(
            pannCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannCategorieLayout.createSequentialGroup()
                .addGroup(pannCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pannCategorieLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(pannCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_IdCategorie)
                            .addComponent(tf_IdCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(pannCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nomCategorie)
                            .addComponent(tf_nomCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(lbl_descriptionCategorie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pannCategorieLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pannCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_nbProduits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_nbProduit))))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        bt_addCategorie.setText("Créer catégorie");
        bt_addCategorie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_addCategorieMouseClicked(evt);
            }
        });

        bt_modifCategorie.setText("Modifier");
        bt_modifCategorie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_modifCategorieMouseClicked(evt);
            }
        });

        bt_supprCategorie.setText("Supprimer");
        bt_supprCategorie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_supprCategorieMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pannBoutonCategorieLayout = new javax.swing.GroupLayout(pannBoutonCategorie);
        pannBoutonCategorie.setLayout(pannBoutonCategorieLayout);
        pannBoutonCategorieLayout.setHorizontalGroup(
            pannBoutonCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannBoutonCategorieLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(bt_addCategorie)
                .addGap(82, 82, 82)
                .addComponent(bt_modifCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(bt_supprCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pannBoutonCategorieLayout.setVerticalGroup(
            pannBoutonCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannBoutonCategorieLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(pannBoutonCategorieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_addCategorie)
                    .addComponent(bt_modifCategorie)
                    .addComponent(bt_supprCategorie))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout tabPannCategoriesLayout = new javax.swing.GroupLayout(tabPannCategories);
        tabPannCategories.setLayout(tabPannCategoriesLayout);
        tabPannCategoriesLayout.setHorizontalGroup(
            tabPannCategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPannCategoriesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabPannCategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pannBoutonCategorie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pannRechercheCategorie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pannCategorie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tabPannCategoriesLayout.setVerticalGroup(
            tabPannCategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPannCategoriesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(pannRechercheCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pannCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pannBoutonCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane_onglets.addTab("Catégories", tabPannCategories);

        javax.swing.GroupLayout tabPannPromotionLayout = new javax.swing.GroupLayout(tabPannPromotion);
        tabPannPromotion.setLayout(tabPannPromotionLayout);
        tabPannPromotionLayout.setHorizontalGroup(
            tabPannPromotionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 728, Short.MAX_VALUE)
        );
        tabPannPromotionLayout.setVerticalGroup(
            tabPannPromotionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        jTabbedPane_onglets.addTab("Promotion", tabPannPromotion);

        pannRechercheClient.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Rechercher un client"));

        lbl_rechercheIdClient.setText("ID client");

        bt_rechercheClient.setText("Recherche");

        bt_rechercheClientEffacer.setText("Effacer");

        lbl_listeClient.setText("Liste client");

        t_listeClient.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        t_listeClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nom", "Prénom"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(t_listeClient);

        javax.swing.GroupLayout pannRechercheClientLayout = new javax.swing.GroupLayout(pannRechercheClient);
        pannRechercheClient.setLayout(pannRechercheClientLayout);
        pannRechercheClientLayout.setHorizontalGroup(
            pannRechercheClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannRechercheClientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pannRechercheClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pannRechercheClientLayout.createSequentialGroup()
                        .addComponent(lbl_rechercheIdClient, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_rechercheClient, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_rechercheClient)
                        .addGap(47, 47, 47)
                        .addComponent(bt_rechercheClientEffacer)
                        .addGap(71, 71, 71))
                    .addGroup(pannRechercheClientLayout.createSequentialGroup()
                        .addComponent(lbl_listeClient, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(311, 311, 311))))
        );
        pannRechercheClientLayout.setVerticalGroup(
            pannRechercheClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannRechercheClientLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pannRechercheClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_rechercheIdClient)
                    .addComponent(tf_rechercheClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pannRechercheClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pannRechercheClientLayout.createSequentialGroup()
                        .addComponent(lbl_listeClient)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pannRechercheClientLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(pannRechercheClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_rechercheClient)
                            .addComponent(bt_rechercheClientEffacer))))
                .addContainerGap())
        );

        pannFicheClient.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_idClient.setText("ID Client");

        lbl_inscription.setText("Date d'inscription");

        ftf_inscription.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        ftf_inscription.setAutoscrolls(false);

        lbl_nomClient.setText("Nom");

        tf_nomClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_nomClientKeyTyped(evt);
            }
        });

        lbl_prenomClient.setText("Prénom");

        tf_prenomClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_prenomClientKeyTyped(evt);
            }
        });

        lbl_emailClient.setText("Email");

        tf_emailClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_emailClientActionPerformed(evt);
            }
        });

        t_commande.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Historique des commandes", "Statut"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(t_commande);

        bt_commandeClient.setText("Accéder à la commande");
        bt_commandeClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_commandeClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pannFicheClientLayout = new javax.swing.GroupLayout(pannFicheClient);
        pannFicheClient.setLayout(pannFicheClientLayout);
        pannFicheClientLayout.setHorizontalGroup(
            pannFicheClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannFicheClientLayout.createSequentialGroup()
                .addGroup(pannFicheClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pannFicheClientLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(pannFicheClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pannFicheClientLayout.createSequentialGroup()
                                .addComponent(lbl_nomClient, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_nomClient, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pannFicheClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(bt_commandeClient)
                                .addGroup(pannFicheClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pannFicheClientLayout.createSequentialGroup()
                                        .addComponent(lbl_emailClient, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_emailClient))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pannFicheClientLayout.createSequentialGroup()
                                        .addComponent(lbl_prenomClient, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tf_prenomClient, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(pannFicheClientLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_idClient, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_idClient, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(lbl_inscription, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftf_inscription, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pannFicheClientLayout.setVerticalGroup(
            pannFicheClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannFicheClientLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pannFicheClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_idClient)
                    .addComponent(tf_idClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_inscription)
                    .addComponent(ftf_inscription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(pannFicheClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pannFicheClientLayout.createSequentialGroup()
                        .addGroup(pannFicheClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nomClient)
                            .addComponent(tf_nomClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pannFicheClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_prenomClient)
                            .addComponent(tf_prenomClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pannFicheClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_emailClient)
                            .addComponent(tf_emailClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(bt_commandeClient))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tabPannClientsLayout = new javax.swing.GroupLayout(tabPannClients);
        tabPannClients.setLayout(tabPannClientsLayout);
        tabPannClientsLayout.setHorizontalGroup(
            tabPannClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPannClientsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabPannClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pannFicheClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pannRechercheClient, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        tabPannClientsLayout.setVerticalGroup(
            tabPannClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPannClientsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pannRechercheClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pannFicheClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane_onglets.addTab("Clients", tabPannClients);

        getContentPane().add(jTabbedPane_onglets, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_addProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addProduitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_addProduitActionPerformed

    private void tf_rechercheNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_rechercheNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_rechercheNomActionPerformed

    private void cbb_rechercheCategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_rechercheCategorieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbb_rechercheCategorieActionPerformed

    private void bt_rechercheProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_rechercheProduitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_rechercheProduitActionPerformed

    private void bt_rechercheProduitEffacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_rechercheProduitEffacerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_rechercheProduitEffacerActionPerformed

    private void bt_supprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_supprimerMouseClicked
        if(evt.getSource()== bt_supprimer){
            int reponse = JOptionPane.showConfirmDialog(this,"Êtes-vous sûr de vouloir supprimer ce produit ?","Confirmation",JOptionPane.YES_NO_OPTION);
            if(reponse == 0){
               JOptionPane.showMessageDialog(this,"Le produit a bien été supprimé","Produit supprimé !", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_bt_supprimerMouseClicked

    private void bt_addProduitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_addProduitMouseClicked
        if(evt.getSource()== bt_addProduit){
            JOptionPane.showMessageDialog(pannBoutonProduit,"Le produit a bien été ajouté","Produit ajouté !", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_bt_addProduitMouseClicked

    private void bt_modifierProduitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_modifierProduitMouseClicked
        if(evt.getSource() == bt_modifierProduit){
           int reponse = JOptionPane.showConfirmDialog(this,"Êtes-vous sûr de vouloir modifier ce produit ?","Confirmation",JOptionPane.YES_NO_OPTION);
           if(reponse == 0){
               JOptionPane.showMessageDialog(this,"Le produit a bien été modifié","Produit modifié !", JOptionPane.INFORMATION_MESSAGE);
           }
        }     
    }//GEN-LAST:event_bt_modifierProduitMouseClicked

    private void bt_parcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_parcourirActionPerformed
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        // filtrer les fichiers
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images","jpg","png");
        file.addChoosableFileFilter(filter);
        int res = file.showSaveDialog(null);
        // si l'utilisateur clique sur enregistrer dnas JFileChooser
        if(res == JFileChooser.APPROVE_OPTION){
            File selFile = file.getSelectedFile();
            String path = selFile.getAbsolutePath();
            lbl_image.setIcon(resize(path));
        }
    }//GEN-LAST:event_bt_parcourirActionPerformed

    private void rbt_nonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_nonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_nonActionPerformed

    private void cbb_categorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_categorieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbb_categorieActionPerformed
    
    // Méthode empêchant la saisie autre que saisie numérique
    private void tf_prixPromoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_prixPromoKeyTyped
        char c = evt.getKeyChar();
        if(((c <'0')|| (c >'9')) && (c != KeyEvent.VK_BACK_SPACE)){
            evt.consume(); // ignorer l'événement
        }
    }//GEN-LAST:event_tf_prixPromoKeyTyped
    
    // Méthode empêchant la saisie autre que saisie numérique
    private void tf_prixKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_prixKeyTyped
        char c = evt.getKeyChar();
        if(((c <'0')|| (c >'9')) && (c != KeyEvent.VK_BACK_SPACE)){
            evt.consume(); // ignorer l'événement
        }
    }//GEN-LAST:event_tf_prixKeyTyped

    private void bt_addProduit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_addProduit1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_addProduit1MouseClicked

    private void bt_addProduit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addProduit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_addProduit1ActionPerformed

    private void bt_modifier1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_modifier1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_modifier1MouseClicked

    private void bt_supprimer1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_supprimer1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_supprimer1MouseClicked

    // Méthode empêchant la saisie numérique & caractères spéciaux
    private void tf_nomClientKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nomClientKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE))){
            evt.consume(); // ignore la saisie
        }
    }//GEN-LAST:event_tf_nomClientKeyTyped
    
    // Méthode empêchant la saisie numérique & caractères spéciaux
    private void tf_prenomClientKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_prenomClientKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE))){
            evt.consume(); // ignore la saisie
        }
    }//GEN-LAST:event_tf_prenomClientKeyTyped

    private void tf_emailClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_emailClientActionPerformed
        String email = tf_emailClient.getText();
        if (!email.contains("@")) {
            JOptionPane.showMessageDialog(null, "Veuillez entrer une adresse mail"); 
        }
    }//GEN-LAST:event_tf_emailClientActionPerformed

    private void bt_commandeClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_commandeClientActionPerformed
        FenCommande CommandeId = new FenCommande();
        CommandeId.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_commandeClientActionPerformed

    private void tf_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_stockActionPerformed
        
    }//GEN-LAST:event_tf_stockActionPerformed
    
    // Méthode empêchant la saisie autre que numérique
    private void tf_stockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_stockKeyTyped
        char c = evt.getKeyChar();
        if(((c <'0')|| (c >'9')) && (c != KeyEvent.VK_BACK_SPACE)){
            evt.consume(); // ignorer l'événement
        }
    }//GEN-LAST:event_tf_stockKeyTyped

    // Méthode empêchant la saisie de charactères autre que numérique
    private void tf_seuilAlerteStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_seuilAlerteStockKeyTyped
        char c = evt.getKeyChar();
        if(((c <'0')|| (c >'9')) && (c != KeyEvent.VK_BACK_SPACE)){
            evt.consume(); // ignorer l'événement
        }
    }//GEN-LAST:event_tf_seuilAlerteStockKeyTyped

    private void bt_rechercheCategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_rechercheCategorieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_rechercheCategorieActionPerformed

    // Méthode empêchant la saisie autre que numérique
    private void tf_nbProduitsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nbProduitsKeyTyped
        char c = evt.getKeyChar();
        if(((c <'0')|| (c >'9')) && (c != KeyEvent.VK_BACK_SPACE)){
            evt.consume(); // ignorer l'événement
        }
    }//GEN-LAST:event_tf_nbProduitsKeyTyped

    private void bt_addCategorieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_addCategorieMouseClicked
        if(evt.getSource()== bt_addCategorie){
            JOptionPane.showMessageDialog(pannBoutonCategorie,"La catégorie a bien été ajouté","Catégorie ajoutée !", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_bt_addCategorieMouseClicked

    private void bt_modifCategorieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_modifCategorieMouseClicked
        if(evt.getSource() == bt_modifCategorie){
           int reponse = JOptionPane.showConfirmDialog(this,"Êtes-vous sûr de vouloir modifier cette catégorie ?","Confirmation",JOptionPane.YES_NO_OPTION);
           if(reponse == 0){
               JOptionPane.showMessageDialog(this,"La catégorie a bien été modifié","Catégorie modifiée !", JOptionPane.INFORMATION_MESSAGE);
           }
        }     
    }//GEN-LAST:event_bt_modifCategorieMouseClicked

    private void bt_supprCategorieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_supprCategorieMouseClicked
        if(evt.getSource()== bt_supprCategorie){
            int reponse = JOptionPane.showConfirmDialog(this,"Êtes-vous sûr de vouloir supprimer cette catégorie ?","Confirmation",JOptionPane.YES_NO_OPTION);
            if(reponse == 0){
               JOptionPane.showMessageDialog(this,"La catégorie a bien été supprimé","Catégorie supprimée !", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_bt_supprCategorieMouseClicked

    // Méthode pour redimensionner l'image avec la même taille que celle du label
    private ImageIcon resize(String imgPath) {
        ImageIcon path = new ImageIcon(imgPath);
        Image img = path.getImage();
        Image newImg = img.getScaledInstance(lbl_image.getWidth(),lbl_image.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btGroup_promo;
    private javax.swing.JButton bt_addCategorie;
    private javax.swing.JButton bt_addProduit;
    private javax.swing.JButton bt_addProduit1;
    private javax.swing.JButton bt_commandeClient;
    private javax.swing.JButton bt_modifCategorie;
    private javax.swing.JButton bt_modifier1;
    private javax.swing.JButton bt_modifierProduit;
    private javax.swing.JButton bt_parcourir;
    private javax.swing.JButton bt_rechercheCategorie;
    private javax.swing.JButton bt_rechercheClient;
    private javax.swing.JButton bt_rechercheClientEffacer;
    private javax.swing.JButton bt_rechercheProduit;
    private javax.swing.JButton bt_rechercheProduitEffacer;
    private javax.swing.JButton bt_supprCategorie;
    private javax.swing.JButton bt_supprimer;
    private javax.swing.JButton bt_supprimer1;
    private javax.swing.JComboBox<String> cbb_categorie;
    private javax.swing.JComboBox<String> cbb_categorie2;
    private javax.swing.JComboBox<String> cbb_rechercheCategorie;
    private javax.swing.JFormattedTextField ftf_inscription;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane_onglets;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_IdCategorie;
    private javax.swing.JLabel lbl_categorie;
    private javax.swing.JLabel lbl_categorie1;
    private javax.swing.JLabel lbl_description;
    private javax.swing.JLabel lbl_descriptionCategorie;
    private javax.swing.JLabel lbl_emailClient;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_idClient;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JLabel lbl_inscription;
    private javax.swing.JLabel lbl_listeClient;
    private javax.swing.JLabel lbl_nbProduit;
    private javax.swing.JLabel lbl_nom;
    private javax.swing.JLabel lbl_nomCategorie;
    private javax.swing.JLabel lbl_nomClient;
    private javax.swing.JLabel lbl_prenomClient;
    private javax.swing.JLabel lbl_prix;
    private javax.swing.JLabel lbl_prixPromo;
    private javax.swing.JLabel lbl_promotion;
    private javax.swing.JLabel lbl_rechercheCategorie;
    private javax.swing.JLabel lbl_rechercheIdClient;
    private javax.swing.JLabel lbl_rechercheNom;
    private javax.swing.JLabel lbl_stock;
    private javax.swing.JPanel pannBouton1;
    private javax.swing.JPanel pannBoutonCategorie;
    private javax.swing.JPanel pannBoutonProduit;
    private javax.swing.JPanel pannCaractProduit;
    private javax.swing.JPanel pannCatalogueProduits;
    private javax.swing.JPanel pannCategorie;
    private javax.swing.JPanel pannFicheClient;
    private javax.swing.JPanel pannRechercheCategorie;
    private javax.swing.JPanel pannRechercheClient;
    private javax.swing.JRadioButton rbt_non;
    private javax.swing.JRadioButton rbt_oui;
    private javax.swing.JTable t_commande;
    private javax.swing.JTable t_listeClient;
    private javax.swing.JTextArea ta_descriptionCategorie;
    private javax.swing.JTextArea ta_descriptionCategorie1;
    private javax.swing.JPanel tabPannCategories;
    private javax.swing.JPanel tabPannClients;
    private javax.swing.JPanel tabPannProduits;
    private javax.swing.JPanel tabPannPromotion;
    private javax.swing.JTextField tf_IdCategorie;
    private javax.swing.JTextField tf_emailClient;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_idClient;
    private javax.swing.JTextField tf_nbProduits;
    private javax.swing.JTextField tf_nom;
    private javax.swing.JTextField tf_nomCategorie;
    private javax.swing.JTextField tf_nomClient;
    private javax.swing.JTextField tf_prenomClient;
    private javax.swing.JTextField tf_prix;
    private javax.swing.JTextField tf_prixPromo;
    private javax.swing.JTextField tf_rechercheClient;
    private javax.swing.JTextField tf_rechercheNom;
    private javax.swing.JTextField tf_seuilAlerteStock;
    private javax.swing.JTextField tf_stock;
    // End of variables declaration//GEN-END:variables
    
}
