/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ptut.vue;

import java.awt.Desktop;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Florian Hauwelle
 */
public class FenConnexion extends javax.swing.JFrame {

    /**
     * Creates new form FenConnexion
     */
    public FenConnexion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pannConnexion = new javax.swing.JPanel();
        lbl_imgLogin = new javax.swing.JLabel();
        lbl_utilisateur = new javax.swing.JLabel();
        lbl_mdp = new javax.swing.JLabel();
        tf_utilisateur = new javax.swing.JTextField();
        pwd_mdp = new javax.swing.JPasswordField();
        pannBouton = new javax.swing.JPanel();
        bt_mdpOublie = new javax.swing.JButton();
        bt_connexion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Connexion");

        lbl_imgLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.jpg"))); // NOI18N

        lbl_utilisateur.setText("Utilisateur");

        lbl_mdp.setText("Mot de passe");

        pwd_mdp.setText("login");

        javax.swing.GroupLayout pannConnexionLayout = new javax.swing.GroupLayout(pannConnexion);
        pannConnexion.setLayout(pannConnexionLayout);
        pannConnexionLayout.setHorizontalGroup(
            pannConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannConnexionLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(pannConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_utilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pannConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_utilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwd_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_imgLogin))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        pannConnexionLayout.setVerticalGroup(
            pannConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannConnexionLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lbl_imgLogin)
                .addGap(76, 76, 76)
                .addGroup(pannConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_utilisateur)
                    .addComponent(tf_utilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(pannConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_mdp)
                    .addComponent(pwd_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        getContentPane().add(pannConnexion, java.awt.BorderLayout.CENTER);

        bt_mdpOublie.setText("Mot de passe oublié ?");
        bt_mdpOublie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_mdpOublieActionPerformed(evt);
            }
        });

        bt_connexion.setText("Connexion");
        bt_connexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_connexionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pannBoutonLayout = new javax.swing.GroupLayout(pannBouton);
        pannBouton.setLayout(pannBoutonLayout);
        pannBoutonLayout.setHorizontalGroup(
            pannBoutonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannBoutonLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(bt_connexion, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(bt_mdpOublie)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        pannBoutonLayout.setVerticalGroup(
            pannBoutonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannBoutonLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(pannBoutonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_mdpOublie)
                    .addComponent(bt_connexion))
                .addGap(33, 33, 33))
        );

        getContentPane().add(pannBouton, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_connexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_connexionActionPerformed
        FenAccueil FenMain = new FenAccueil();
        FenMain.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_connexionActionPerformed

    private void bt_mdpOublieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_mdpOublieActionPerformed
        if(evt.getSource()== bt_mdpOublie){
            JOptionPane.showMessageDialog(null,"Nous ne pouvons pas vous aider","Zut...", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bt_mdpOublieActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_connexion;
    private javax.swing.JButton bt_mdpOublie;
    private javax.swing.JLabel lbl_imgLogin;
    private javax.swing.JLabel lbl_mdp;
    private javax.swing.JLabel lbl_utilisateur;
    private javax.swing.JPanel pannBouton;
    private javax.swing.JPanel pannConnexion;
    private javax.swing.JPasswordField pwd_mdp;
    private javax.swing.JTextField tf_utilisateur;
    // End of variables declaration//GEN-END:variables
}
